Masterminds/sprig

README.md, functions.go, functions_test.go, glide.lock, glide.yaml
Adds a UUIDv4 function provided by https://github.com/satori/go.uuid/ that takes no parameters.
=> Add UUIDv4 function

functions.go, functions_test.go
It's workaround for https://github.com/kubernetes/helm/issues/1524
=> Fix to int64 convert documentation. Add new toInt function

README.md
In #24 I think I assumed that my godoc would also update the README, which appears not to be the case. This adds documentation for the new file helpers.
=> Update readme with new file methods

README.md, functions.go, functions_test.go, glide.lock, glide.yaml
derivePassword derives a password from a given master password and a set of other parameters.
The tests are variants of the input comparing it to the reference implementation.
=> Added derivePassword implementing Master Password

functions.go, functions_test.go, glide.lock
I think we can add more functions based on this [xstrings](https://github.com/huandu/xstrings)
=> Add 'snakecase', 'camelcase' and 'shuffle'

docs/strings.md, functions.go, regex.go, regex_test.go
https://github.com/Masterminds/sprig/issues/39
=> Added basic regex functionality

docs/math.md, functions.go, numeric.go, numeric_test.go
per request: https://github.com/Masterminds/sprig/issues/34
=> Added ceil floor and round functions

doc.go
Noticed the godoc was stale. Added missing funcs
=> add new string funcs to godoc

crypto.go, crypto_test.go, docs/crypto.md, functions.go
=> add cert-generation functions

defaults.go, defaults_test.go, doc.go, docs/defaults.md, functions.go
Helps out with scoping in templates
=> Add ternary function

glide.lock, glide.yaml
https://github.com/satori/go.uuid/commit/0ef6afb
=> fix signature mismatch for call to uuid.NewV4

crypto.go, glide.lock, glide.yaml
A breaking change was introduced by the commit
https://github.com/satori/go.uuid/commit/0ef6afb
=> replace satori/go.uuid with google/uuid

docs/strings.md, functions.go, functions_test.go, glide.lock
Added kebabcase that was added to huandu/xstrings that sprig already uses. See https://github.com/huandu/xstrings/issues/41 for more info on adding the kebabcase function to xstrings.
=> Added kebabcase function

crypto.go, crypto_test.go, docs/crypto.md, functions.go
Just like the title says: Adds an alder32sum function, test, and docs entry.
=> Adds adler32sum function and test

docs/strings.md
=> Improve documentation of regexMatch function

docs/strings.md
Adds the documentation for:
- trimPrefix
- swapcase
=> doc: adds missing documentation.

docs/strings.md, strings.go
Fixes: https://github.com/Masterminds/sprig/issues/130
* Updated documentation to reflect how substr function works
* Updated comments and var names in substr to reflect how it is actually working
=> Fix substr docs and var names

README.md
Hi there, @Feedmereadmes finally getting around to this. Edits in file, suggestions here:
**Files to add**
- Add a CONTRIBUTING.md so people can follow your style and process preferences. You could also use that file to say which functions you want (those fitting your principles) and don't want (those that don't).
- Add a Code of Conduct so people know you'll welcome them and they'll feel safer helping you. (More context: http://opensourcesurvey.org/2017/)
- consider adding some of the Go-related badges: godoc, Go Report, etc.
**Your README: content suggestions**
For the intro paragraph, consider which of these questions would make your project more understandable/really enrich and clarify the answer, "what does it do?"
— Describe very briefly but clearly what the project does.
— State if …
=> README edits/fixes/suggestions

docs/date.md
Correct "formates". Should be "formats".
=> htmlDate doc formatEs

docs/reflection.md
typeIsLike works as typeIs instead of kindIs.
=> typeIsLike works as typeIs

docs/strings.md
=> trimPrefix trims prefix

docs/date.md
Example for dateInZone uses date function, updated to use correct function.
=> Fix dateInZone doc example

crypto.go, crypto_test.go, docs/crypto.md, functions.go
Adds simple text encryption with the AES-256 CBC algorithm.
=> Add encryptAES/decryptAES functions

docs/url.md, functions.go, url.go, url_test.go
New functions to parse and join back URLs
Motivation: useful to break down input URL into parts, to pass to some consumer
=> feat: url parse and join functions

dict.go, dict_test.go, docs/dicts.md, docs/index.md, functions.go, go.mod, go.sum
=> Add deepCopy and mustDeepCopy functions

README.md
I've added the godoc badge and the go-report-card badge making it easier for users to access documentation and find potential errors that could be fixed to improve the code quality.
=> Godoc badge and go-report-card

CHANGELOG.md
=> Updating changelong in preperation for a release

go.mod, go.sum
=> Updating to semver v3.0.3 to fix issue with <= ranges

date.go, date_test.go, docs/date.md, functions.go
Signed-off-by: Joe Groocock <me@frebib.net>
=> Add duration filter

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
The body of the templates messages has been ending up in issues/PRs.
Making them a comment so they do not display.
=> Updating templates for GitHub

.github/workflows/test.yaml, CHANGELOG.md, README.md
=> Preparing for the 3.1.0 release

docs/date.md
=> Fix htmlDateInZone example

docs/reflection.md
Fixes: https://github.com/Masterminds/sprig/issues/259
Make all entries in docs match entries in functions.go:
https://github.com/Masterminds/sprig/blob/4241ae82dd07e5d3391a83c25b79c04450eb22b0/functions.go#L236
=> Fix typo in isKind docs

docs/index.md, docs/paths.md, functions.go, functions_linux_test.go, functions_windows_test.go
Tests pass on Windows and *should* pass on Linux too.
=> Added functions to process filepaths via the path/filepath package

.github/workflows/test.yaml, crypto.go, crypto_test.go, go.mod, go.sum, network.go
=> Add testing for Go 1.15 and drop testing for Go 1.12

CHANGELOG.md
=> Updating changelog for 3.2.0 release

CHANGELOG.md, go.mod, go.sum
Update to the latest goutils
Signed-off-by: Matt Butcher <matt.butcher@microsoft.com>
=> Updated to goutils 1.1.1

docs/mathf.md
Changes:
- **[docs/mathf.md]**
- Changes `addf` to `mulf` in its section;
- Changes `min` to `minf`.
=> docs: Fix typo

go.mod, go.sum
=> Updating semver package

.github/workflows/test.yaml
=> Updating the Go versions used in testing

CHANGELOG.md
This fixes a typo in the changelog.
=> Change intial to initial.

docs/dicts.md
=> correct value

dict.go, go.mod, go.sum
The mergo dependency moved to a new location and has had some releases.
=> Updating location of mergo
