Masterminds/sprig

functions.go
The functions in hermeticMap should always produce exactly the same output given the same input, no matter what machine / user / geographical location / timezone / environment they are executed on.
=> Separate non-reproducible functions from the others.

functions.go, functions_test.go
This function generates a new crypto key based on the crypto type. By default the type is "rsa".
Addresses use cases like ours at deis/charts#237, where [helm](http://helm.sh/) uses sprig for its templates. This is useful for us so we can generate rsa/dsa/ecdsa private keys on the fly without having to hard-code the keys in the templates.
Note that this bumps up the unit test time significantly (~11 seconds on my machine) from a few milliseconds due to the amount of time it takes to compute and generate a new crypto key each time the function is called.
if this doesn't seem fitting for sprig, I'd be more than happy to PR this against helm; I just thought these functions might be useful to someone else (or it could just be us that generates RSA keys on the fly, which is cool too). :)
=> add genPrivateKey function

README.md, functions.go, functions_test.go
As agreed in https://github.com/kubernetes/helm/pull/1513
I switched back to hex encoding as this is what people expect.
=> add sha256sum

functions.go, functions_test.go
These template functions should make working with paths easier.
=> feat(sprig): Add file path utility funcs from stdlib `path`.

.gitignore, .travis.yml
The tests added for set/unset rely on the template space-trimming
feature added in 1.6, and it's reasonable to only support 1.6+ anyways.
Because of the 1.6-requiring changes, travis has been failing on master for a bit.
cc @technosophos since your commit was the one to introduce 1.6 features.
=> Update travis-ci tested versions

dict.go, dict_test.go, functions.go, glide.lock, glide.yaml
Adds a merge function using https://github.com/imdario/mergo.
For https://github.com/prydonius/common-chart/tree/merge-approach in Helm. I've left out MergeWithOverwrite and other functions for now as there may be compatibility issues in Helm. Want to see if we can get this working as-is with Helm, and add the other functions after. cc @technosophos
=> add merge function to dict

dict.go, dict_test.go, docs/dicts.md
Takes multiple sources for dict merging instead of just one, because `{{ merge $dest (merge $source1 $source2) }}` is inconvenient.
=> dict/merge: Add ability to merge multiple dicts, update test and docs

doc.go, docs/strings.md, functions.go, strings.go, strings_test.go
Convenience function for working with YAML files, among other things.
```go
{{ $foo := "bar\nbaz" }}
key: |-
{{- indent 2 $foo }}
```
will produce:
```yaml
key: |-  bar
baz
```
We could unindent, and not use white space trimming (`{{` vs `{{-`), but this breaks visual consistency. Another solution may be to pipe to an additional print, but this is inconvenient.
```go
{{ $foo := "bar\nbaz" }}
key: |-
{{- nindent 2 $foo }}
```
will produce:
```yaml
key: |-
bar
baz
```
=> strings: Add nindent function

docs/strings.md
The line contained {{ which is a control character for liquid
templates used by github pages that generated the docs site. With
that in the page and not being closed an error about it not being
closed occured and github pages stopped updating.
Removing the sentence with the usage of that to remove the error.
=> Removing line with {{ due to blocking github pages genertion

.travis.yml, dict_test.go, functions.go, list.go, list_test.go, strings_test.go
The list functions used to only handle reveiving []interface{}. The
output of regex and some other functions provided []string which is
not compatible. This approach enables list to handle other types
of slices and convert them for a unified output.
Closes #63
Closes #59 
/cc @technosophos
=> Update the list functions to handle int, string, and other slices

docs/defaults.md
Hi. Following functions are not mentioned in the Sprig documentation.
- `toJson`
- `toPrettyJson`
I have added them to docs in this PR.
=> Add json helpers to docs

dict.go, dict_test.go, doc.go, docs/dicts.md
Get keys from multiple dicts--original functionality is preserved. Need this for Helm in configmaps and secrets.
=> dict: allow keys function to take multiple dicts

crypto.go, crypto_test.go, docs/crypto.md, functions.go
- This implements https://github.com/Masterminds/sprig/issues/88
- In many projects you need the sha1sum (e.g. in Jenkins for script approval)
=> Added sha1sum to crypto functions

crypto.go, crypto_test.go, docs/crypto.md, functions.go
Some charts may want to use a custom Root CA to generate signed certificates, this patch implements this requirement.
* In values.yaml
```
root_key: base64-encoded-key
root_ca: base64-encoded-crt
```
* In templates
```
{{- $ca := buildCustomCert .Values.root_key .Values.root_ca }}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- $cn := printf "%s-%s" $name .Release.Name | trunc 63 -}}
{{- $altName1 := printf "%s.%s" $cn .Release.Namespace }}
{{- $altName2 := printf "%s.%s.svc" $cn .Release.Namespace }}
{{- $cert := genSignedCert $cn nil (list $altName1 $altName2) 3650 $ca }}
```
=> Allow customizing Root CA that used by genSignedCert

docs/string_slice.md, functions.go, strings.go, strings_test.go
uses strings.SplitN functionality - Intentionally leaving out splitnList since it didn't seem to provide value here
=> add splitn function

dict.go, dict_test.go, doc.go, docs/dicts.md, functions.go
Create the `values` function, defined on a `dict`, that is the
complement to `keys` function. `values` returns an interface{} list of
all values in a dict.
=> Extract values of dict with `values` function

docs/crypto.md
The example listed for `buildCustomCert` has the parameters reversed
from what is implemented in [0]. This patch set fixes the doc to match
the implementation.
[0] https://github.com/Masterminds/sprig/blob/6b2a58267f6a8b1dc8e2eb5519b984008fa85e8c/crypto.go#L166
Signed-off-by: Tin Lam <tin@irrational.io>
=> Fix example for buildCustomCert

crypto.go, crypto_test.go
All TLS certificates that are generated have a hard coded Serial Number of 1. This causes verification issues since Serial Numbers are supposed to be a positive unique number.
Example:
```
$ curl --version
curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.28.4 zlib/1.2.7 libidn/1.28 libssh2/1.4.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz unix-sockets
$ curl -v --cacert /ca.crt https://test.example.com
...
* NSS error -8054 (SEC_ERROR_REUSED_ISSUER_AND_SERIAL)
* You are attempting to import a cert with the same issuer/serial as an existing cert, but that is not the same cert.
...
```
Implementation based on …
=> Generate Serial Number for TLS certs

docs/lists.md
Fixes: https://github.com/Masterminds/sprig/issues/116
Fixes: https://github.com/Masterminds/sprig/issues/98
(Duplicate Issues)
Fix the argument order of 'has' documentation example
(Thanks @andreas-kupries for the following description of the issue:)
The list function has is implemented as `has needle haystack`
See: https://github.com/Masterminds/sprig/blob/master/list.go#L241
The documentation at https://github.com/Masterminds/sprig/blob/master/docs/lists.md
on the other hand claims the reverse: `has haystack needle`.
=> Fix 'has' documentation

strings.go, strings_test.go
Before golang 1.11, untyped nil values would not be passed to template function used in the text/template package. This changed in 1.11 as described [here](https://golang.org/doc/go1.11#text/template). Some of the string functions does not handle nil values in a sensible way, for example passing nil to `quote` results in the string `"<nil>"`. This PR fixes the string functions to handle untyped nil values.
This issue causes problems for some Helm charts as described in https://github.com/helm/helm/issues/5049
=> Handle untyped nil values as parameters to string functions

list.go, list_test.go
When iterating through multiple lists, possibly including nil entries, it's useful for the "has" function to gracefully handle nil values.
For example, instead of panicking, the following template should return false, since trivially, a value cannot exist in an empty and/or nil list:
`{{ has "bar" nil }}`
This pull request adds a check for this trivial case before the reflection, so the function returns false instead of triggering a panic.
=> Gracefully handle nil list in "has" function

docs/strings.md, functions.go, functions_test.go, glide.lock, strings.go, strings_test.go
This PR surfaces the random string functions that utilize ```crypto/rand``` that were added to ```goutils``` here: https://github.com/Masterminds/goutils/pull/25. This will allow Go templates to utilize random strings that have been generated in a cryptographically secure way.
I made the functions accessible by surfacing them through ```strings.go```. I bounced back and forth between thinking they should be in ```strings.go``` and ```crypto.go``` a few times. If you think they should be made available via ```crypto.go``` instead, just let me know.
@technosophos
=> Surface cryptographically secure random strings from goutils

docs/strings.md, functions.go, strings.go, strings_test.go
As discussed in https://github.com/Masterminds/sprig/pull/135, this PR makes the random string generators in Sprig use the cryptographically secure generators (backed by `crypto/rand`) from `Masterminds/goutils` by default.
See the comment https://github.com/Masterminds/sprig/pull/135#issuecomment-451345233 through to the end for more context and performance testing metrics.
@technosophos
=> Make random string functions use crypto by default

strings.go, strings_test.go
```
panic: runtime error: slice bounds out of range [recovered]
panic: runtime error: slice bounds out of range
goroutine 1 [running]:
text/template.errRecover(0xc420115b10)
/go/src/text/template/exec.go:137 +0x1d4
panic(0x689de0, 0x83b570)
/go/src/runtime/panic.go:502 +0x229
github.com/Masterminds/sprig.substring(0x0, 0xa, 0xc42016e024, 0x3, 0x0, 0x0)
/gopath/src/github.com/Masterminds/sprig/strings.go:209 +0xbf
reflect.Value.call(0x686ea0, 0x6e24e8, 0x13, 0x6cc806, 0x4, 0xc420176140, 0x3, 0x3, 0x6cb260, 0x6b2601, ...)
/go/src/reflect/value.go:447 +0x969
reflect.Value.Call(0x686ea0, 0x6e24e8, 0x13, 0xc420176140, 0x3, 0x3, 0x670380, 0xc420172090, 0x98)
/go/src/reflect/value.go:308 +0xa4
text/template.(*state).evalCall(0xc420115a90, 0x688b20, 0xc4201602d0, 0x15, 0x686ea0, 0x6e24e8, 0x13, …
```
=> Fix substr panic

functions.go
Hi, we updated some exported function comments based on best practices from Effective Go. It’s admittedly a relatively minor fix up. Does this help you?
=> Fix function comments based on best practices from Effective Go

date.go, date_test.go, docs/date.md, functions.go
It appears there is no format option for golang time to print out the seconds since the unix epoch. So, here is a template function to do that.
=> Adding function to get unix epoch for a time

docs/crypto.md
masterpassword "well specified" link is no longer available. Replacing it with link to PDF.
=> masterpassword algo page unavailable

docs/index.md
Index page convention seems to be: 
1. group functions by category
2. list all functions in a category
3. or list some functions in a category (likely the most used) and suggest with ", etc." there are more functions to discover by following the link
"Default Functions" breaks this assumption by presenting a list not followed by "etc." that is shorter than the one presented by defaults.md ("ternary" function is missing).
Here we can either add "ternary" to the list or append "etc." and maybe shorten the list of presented functions from 5 elements to 3.
=> Default Functions missing ternary or etc

docs/index.md
.etc missing next to "Cryptographic and Security Functions" in index page. There are more functions present in crypto.md than the ones listed by index.
=> Crypto and Security functions index missing etc

docs/strings.md
kebabCase should be "kebabcase". See:
https://github.com/Masterminds/sprig/blob/2625cd487a689ca112e1301a58b89b347ba2c994/functions.go#L132
=> kebabcase is lowercase

docs/dicts.md
Documentation states `values` is similar to `keys` but `keys` supports listing keys from multiple dictionaries while `values` does not. It only supports one dictionary.
=> "values" supports only one dictionary

docs/strings.md
Last parameter of "regexFindAll" is not documented.
It maps to https://golang.org/pkg/regexp/#Regexp.FindAllString 
"These routines take an extra integer argument, n. If n >= 0, the function returns at most n matches/submatches; otherwise, it returns all of them. "
=> regexFindAll documentation missing last parameter

docs/reflection.md, functions.go
I found myself in a situation where I really missed comparing two lists or two maps (mostly in Helm charts). I think `deepEqual` would help there a lot in those situations.
=> add deepEqual function

date.go, date_test.go, functions.go
This pr adds a method to round to the largest duration.
It's pretty inefficient and pretty imprecise, but I think it's mostly fine.
=> Add durationRound function

crypto.go, crypto_test.go, date.go, defaults.go, dict.go, docs/date.md, docs/defaults.md, docs/dicts.md, functions.go, glide.lock, glide.yaml, list.go, numeric.go, reflect_test.go, regex.go, regex_test.go
* tried to satisfy the god of linters;
* replaced explicit and "inherited" panics with error returns (fixes #125), this actually makes much more sense;
* introduced new functions: `mustDateModify`, `mustToDate`, `mustToJson`, `mustToPrettyJson`, `mustMerge` (fixes #115);
* replaced type cast functions with spf13/cast to DRY and not re-invent anything. If for some reason you find this change should be reverted please let me know
=> Properly handle errors

docs/dicts.md, issue_188_test.go
Two things happen here:
1. A test is put into place for this situation to show the merge
with and without a deep copy
2. Documentation is updated to show how to use deepCopy with merging
=> Documenting and testing for deep copying with merging of dicts

docs/strings.md, strings.go, strings_test.go
Closes: https://github.com/Masterminds/sprig/issues/167
```
trunc -5 "hi, world"
// "world"
```
=> Support negative values in trunc

dict.go, dict_test.go, docs/dicts.md, docs/index.md, functions.go
Closes: https://github.com/Masterminds/sprig/issues/151
```
get $myDict "key1"
```
The above returns `"value1"`
=> Add `get` support to dicts

go.mod, go.sum
Semver had an issue with the range ^0.0 that was fixed in 3.0.2
=> Updating semver to 3.0.2

crypto.go, crypto_test.go, docs/crypto.md, functions.go
=> Add support for generating htpasswd hash

docs/integer_slice.md, functions.go, numeric.go, numeric_test.go
=> Add `seq` function

functions.go
No need to wrap these calls in a lambda.
=> Unlambda functions with correct signature

docs/integer_slice.md
Fix a documentation mistake: `seq 5` results in `1 2 3 4 5`, not `0 1 2 3 4 5`
=> Fix `seq` example

LICENSE.txt
The license file was not displaying as MIT on the homepage on GitHub.
Updating the format so it should display as MIT and updating the
years range.
=> Updating license for GitHub display

docs/index.md
The network.md documentation was added in https://github.com/Masterminds/sprig/commit/ac14fb280b0322c1d3494610095ba68698f32bae but was never added to index.md.
=> Add network.md to index.md

crypto.go, crypto_test.go, docs/crypto.md, functions.go
Continues work at #225 by adding a `bcrypt` function. `htpasswd` has been modified to use the `bcrypt` function.
I could've gotten away with using the `htpasswd` function in my app and setting `username` to empty string but then I'd also have to trim off the leading `:`. This seems cleaner for everyone.
cc @rustycl0ck
=> Add a bcrypt function

crypto.go, crypto_test.go, docs/crypto.md, functions.go
Adds the randBytes function to cryptographically generate a base64-encoded string of random bytes of a given length.
Resolves #252.
=> Add randBytes

dict.go, dict_test.go, docs/dicts.md, docs/index.md, functions.go
Adds a pipeline-compatible `dig` function - traverses a list of keys to
return a value, or a default if no value provided.
Future work, if required: allow `dig` to walk into lists with numeric
indexes.
Closes #227
=> Dig into dict

docs/strings.md, functions.go, functions_test.go, regex.go, regex_test.go
I'd like to be able to get a regex to match to a particular string in the file generated from a go template. This would enable that easily, and uses the existing golang regex package. This PR includes an addition to the docs.
Let me know if I need to make any edits or changes. 
Thank you!
=> Add support for regex.QuoteMeta string conversion

defaults.go, defaults_test.go, docs/defaults.md, functions.go
port any/all function from other language(e.g. python), it already widely used (in us) internally.
=> add all/any for evaluating multiple conditions

docs/lists.md, functions.go, list.go, list_test.go
this was a function that I found helpful to have.
I tried to follow your style.
=> Add `chunk` function to split array into smaller

go.mod, go.sum
mergo had made a breaking change in 0.3.9. This was undone in 0.3.10
with a new path forward for internal reworking via a new implementation.
0.3.10 and 0.3.11 no longer break sprig functionality. This is tested.
More information at https://github.com/imdario/mergo/releases/tag/v0.3.10
=> Updating mergo to 0.3.11

README.md, docs/mathf.md
Changes:
- [Readme.md] Update sprig version to v3 in ``Usage`` section
- [doc/mathf.md] Fix a typo
=> Fix some typo in doc

docs/semver.md
The return value for `semverCompare` was not explicitly listed in the docs,
and I had to go check in the source code wether it's actually a boolean.
By listing the return type in the docs, we can make usage easier for other people.
=> docs: clarify semverCompare return value

docs/date.md
`duration 95` returns 0, as it doesn't satisfy the types(string, int64) present in the switch statement. So the example should show `duration "95"`
=> Show correct usage of duration

.github/workflows/test.yaml
=> Updating testing to include Go 1.19.

docs/index.md
URL parsing seemed like something that would be in sprig, but I didn't find it in the docs. When looking for a discussion about it, it turns out the code and docs were already there since a long time ago, just the link was missing! This PR adds the missing link.
=> docs: Add missing link to url functions

docs/mathf.md
=> Removing duplicate documentation

CHANGELOG.md
=> Updating the changelog for the 3.3.0 release

docs/crypto.md
Updates the derivePassword reference paper URL.
The original link, https://masterpassword.app/masterpassword-algorithm.pdf is a 404 at present. The company [re-branded](https://spectre.app/blog/2021-10-31-spectre-ios-launch/) and changed the algorithm description PDF's filename (though amusingly not any of the references to the old name in the PDF's contents).
As best I can tell, https://spectre.app/spectre-algorithm.pdf is the current home of the previous document.
https://spectre.app/blog/2018-01-06-algorithm/ appears to describe the same in HTML form. Dunno if that'd be preferable. Unfortunately I couldn't find something that looked like it'd be a long-lived simple description of the algorithm in RFC format or similar.
=> chore: update derivePassword URL

crypto.go, crypto_test.go, docs/crypto.md
My use case is to address hashicorp vault > external-password > k8s password > envoy gateway > envoy
envoy only supports sha encoding, external-password uses sprig, sprig encodes to bcrypt
This PR will allow to simplify this chain and partially fix #32.
I've opened a counterpart issue in envoy repo to also add bcrypt decoding support https://github.com/envoyproxy/envoy/issues/36278
I hope this will be fixed both ways, allowing better security with a smooth transition from sha to bcrypt on existing apps
=> add SHA support to htpasswd
